## 00.getting started 
1. how to print
2. assing variables
3. commet
4. syntax for basic math

In [1]:
println("I'm excited to learn Julia!")

I'm excited to learn Julia!


In [2]:
my_answer = 42
typeof(my_answer)

Int64

In [3]:
my_pi = 3.14159
typeof(my_pi)

Float64

In [4]:
😺 = "smiley cat!"
typeof(😺)

String

In [5]:
\:smiAssertionError

LoadError: syntax: "\" is not a unary operator

In [6]:
a = 0
b = -1
b + a == 1

false

In [7]:
# 이렇게 하면 단일 코멘트 달 수 있다

In [8]:
#= 이렇게 하면 멀티 코멘트 달 수 있다
굳이 추가 # 를 달지 않아도 가능하다
맨 마지막 =#
println(a + b)

-1


In [9]:
sum = 3 + 7

10

In [10]:
difference = 10 - 3

7

In [11]:
product = 20 * 5

100

In [12]:
quotient = 100 / 10

10.0

In [13]:
power = 10 ^ 2

100

In [14]:
modulus = 101 % 2

1

In [15]:
days = 365
days_float = 365.0

365.0

## 01.String
1. string 넣기
2. string 삽입
3. string 합치기

In [16]:
#1.  " " 또는 """ """ 로 string 만들 수 있음

In [17]:
s1 = "I am a string."
s2 = """I am also a string."""

"I am also a string."

In [18]:
println(typeof(s1), typeof(s2))

StringString


In [19]:
#"Hey, if you use double "" in this"  # error
"""hey, i got "this" clue """

"hey, i got \"this\" clue "

In [20]:
# ' ' 는 string 아니고 Char 
typeof('a')

Char

In [21]:
#2. 문자를 삽입해보자
name = "Jane"
num_fingers = 10
num_toes = 10

10

In [22]:
println("Hello, my name is $name.")
println("I have $num_fingers fingers and $num_toes toes")
println("That is $(num_fingers + num_toes) digits in all!")

Hello, my name is Jane.
I have 10 fingers and 10 toes
That is 20 digits in all!


In [23]:
#3. 문자 합치는 것에는 여러가지 방법이 있다
s3 = "how many cats ";
s4 = " is too many cats?";
cat = 10

10

In [24]:
string(s3, s4)

"how many cats  is too many cats?"

In [25]:
string("idk, but ", cat, " is too few")

"idk, but 10 is too few"

In [26]:
# * 를 사용해서 스트링 합치기도 가능하다
s3 * s4

"how many cats  is too many cats?"

In [27]:
hi = "hi" ^ 1000

"hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihih

In [28]:
a = 3
b = 4
c = "3 + 4"
d = "7"

"7"

## 02. Data structures
1. 튜플
2. 딕셔너리
3. 어레이

In [29]:
#1. 튜플 ? () 로 만들 수 있다
myf_animal = ("penguins","cats","rabbit")
typeof(myf_animal)

Tuple{String,String,String}

In [30]:
myf_animal[1] # 튜플은 1부터 시작한다

"penguins"

In [31]:
#1.1 namedTuples
myf_ = (bird = "penguins", mammal = "cats", fishs = "small_fish")

(bird = "penguins", mammal = "cats", fishs = "small_fish")

In [32]:
myf_[1] == myf_.bird

true

In [33]:
#2. 사전형, 딕셔너리 Dict(key => value)

myp = Dict("jenny" => "1234-5678",
"ella" => "6786-2342")

Dict{String,String} with 2 entries:
  "ella"  => "6786-2342"
  "jenny" => "1234-5678"

In [34]:
myp["ella"]

"6786-2342"

In [35]:
myp["mark"] = "1142-2349"

"1142-2349"

In [36]:
myp

Dict{String,String} with 3 entries:
  "ella"  => "6786-2342"
  "jenny" => "1234-5678"
  "mark"  => "1142-2349"

In [37]:
pop!(myp, "jenny")

"1234-5678"

In [38]:
myp

Dict{String,String} with 2 entries:
  "ella" => "6786-2342"
  "mark" => "1142-2349"

In [39]:
#3. 어레이
myfriends = ["Ted", "ella", "Jamie", "Nill"]

4-element Array{String,1}:
 "Ted"
 "ella"
 "Jamie"
 "Nill"

In [40]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [41]:
fibonacci[3]

2

In [42]:
myfriends[3] = "haha"

"haha"

In [43]:
myfriends

4-element Array{String,1}:
 "Ted"
 "ella"
 "haha"
 "Nill"

In [44]:
push!(fibonacci, 21)

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

In [45]:
pop!(fibonacci) # pop 을 하면 제일 마지막 원소가 사라진다

21

In [46]:
fibonacci

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [47]:
favorites = [["koobideh", "chocolat", "eggs"], ["penguines", "cats", "sugarliders"]]

2-element Array{Array{String,1},1}:
 ["koobideh", "chocolat", "eggs"]
 ["penguines", "cats", "sugarliders"]

In [48]:
numbers = [[1,2,3],[4,5], [6,7,8,9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [49]:
rand(4,3) # 이렇게 하면 랜덤한 값으로 4 x 3 array 행렬을 만든다

4×3 Array{Float64,2}:
 0.350337   0.0357072  0.0361416
 0.0140972  0.203035   0.808335
 0.276643   0.671833   0.191888
 0.755211   0.672356   0.656547

In [50]:
rand(4,3,2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.817096  0.180261  0.830779
 0.460364  0.561718  0.737444
 0.672789  0.291535  0.67781
 0.228496  0.658294  0.62025

[:, :, 2] =
 0.159637  0.494366  0.251214
 0.498299  0.915051  0.654373
 0.16486   0.250831  0.843902
 0.155862  0.58153   0.42329

In [51]:
som = fibonacci # 단순히 복사한 후, 복사행렬의 원소를 바꿔도 동일하게 바뀐다

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [52]:
som[1] = 3333

3333

In [53]:
som

7-element Array{Int64,1}:
 3333
    1
    2
    3
    5
    8
   13

In [54]:
fibonacci

7-element Array{Int64,1}:
 3333
    1
    2
    3
    5
    8
   13

In [55]:
som = copy(fibonacci)

7-element Array{Int64,1}:
 3333
    1
    2
    3
    5
    8
   13

In [56]:
som[1] = 34325

34325

In [57]:
som

7-element Array{Int64,1}:
 34325
     1
     2
     3
     5
     8
    13

In [58]:
fibonacci

7-element Array{Int64,1}:
 3333
    1
    2
    3
    5
    8
   13

In [59]:
#3.1
a_ray = [1,2,3]
push!(a_ray, 333)

4-element Array{Int64,1}:
   1
   2
   3
 333

In [60]:
pop!(a_ray)

333

In [61]:
#myp["Emergency"] = 911
# 타입이 맞지 않다. 맞춰주어야 함
myp["Emergency"] = "911"

"911"

In [62]:
myp

Dict{String,String} with 3 entries:
  "Emergency" => "911"
  "ella"      => "6786-2342"
  "mark"      => "1142-2349"

In [63]:
rand(4, 3)

4×3 Array{Float64,2}:
 0.906229  0.472876  0.345572
 0.512275  0.545004  0.77893
 0.817614  0.798205  0.352131
 0.354755  0.160885  0.718377

## Loops 
- while, for

In [64]:
 n = 0
while n < 10
    global n+=1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [65]:
println(n)

10


In [71]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [72]:
m, n = 5, 5
A = fill(0, (m, n))
for j in 1:n
    for i in 1:m
        A[i, j] = i + j
    end 
end
println(A)

[2 3 4 5 6; 3 4 5 6 7; 4 5 6 7 8; 5 6 7 8 9; 6 7 8 9 10]


In [73]:
B = fill(0, (m, n))
B

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [74]:
for j in 1:n, i in 1:m
    B[i, j] = i + j
    end 
println(B)

[2 3 4 5 6; 3 4 5 6 7; 4 5 6 7 8; 5 6 7 8 9; 6 7 8 9 10]


In [75]:
C  = [i+j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [78]:
for i in 1:100
    println(i^2)
end

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000


In [79]:
B = zeros(m, n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [81]:
for n in 1:10
    A = [i + j for i in 1:n, j in 1:n]
    println(A)
end

[2]
[2 3; 3 4]
[2 3 4; 3 4 5; 4 5 6]
[2 3 4 5; 3 4 5 6; 4 5 6 7; 5 6 7 8]
[2 3 4 5 6; 3 4 5 6 7; 4 5 6 7 8; 5 6 7 8 9; 6 7 8 9 10]
[2 3 4 5 6 7; 3 4 5 6 7 8; 4 5 6 7 8 9; 5 6 7 8 9 10; 6 7 8 9 10 11; 7 8 9 10 11 12]
[2 3 4 5 6 7 8; 3 4 5 6 7 8 9; 4 5 6 7 8 9 10; 5 6 7 8 9 10 11; 6 7 8 9 10 11 12; 7 8 9 10 11 12 13; 8 9 10 11 12 13 14]
[2 3 4 5 6 7 8 9; 3 4 5 6 7 8 9 10; 4 5 6 7 8 9 10 11; 5 6 7 8 9 10 11 12; 6 7 8 9 10 11 12 13; 7 8 9 10 11 12 13 14; 8 9 10 11 12 13 14 15; 9 10 11 12 13 14 15 16]
[2 3 4 5 6 7 8 9 10; 3 4 5 6 7 8 9 10 11; 4 5 6 7 8 9 10 11 12; 5 6 7 8 9 10 11 12 13; 6 7 8 9 10 11 12 13 14; 7 8 9 10 11 12 13 14 15; 8 9 10 11 12 13 14 15 16; 9 10 11 12 13 14 15 16 17; 10 11 12 13 14 15 16 17 18]
[2 3 4 5 6 7 8 9 10 11; 3 4 5 6 7 8 9 10 11 12; 4 5 6 7 8 9 10 11 12 13; 5 6 7 8 9 10 11 12 13 14; 6 7 8 9 10 11 12 13 14 15; 7 8 9 10 11 12 13 14 15 16; 8 9 10 11 12 13 14 15 16 17; 9 10 11 12 13 14 15 16 17 18; 10 11 12 13 14 15 16 17 18 19; 11 12 13 14 15 16 17 18 19 20]


## Functions
- 함수 정의
- duck-typing
- mutating vs. non-mutating
- higer order functions


In [82]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end

function f(x)
    x^2
end


f (generic function with 1 method)

In [83]:
sayhi("lalajin")

Hi lalajin, it's great to see you!


In [84]:
f(50)

2500

In [86]:
sayhi2(name) = println("Hi $name, it's great to see you!")

f2(x) = x^2

sayhi2("lalajin")
f2(50)

Hi lalajin, it's great to see you!


2500

In [87]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x^2

sayhi3("lalajinjin")
f3(40)

Hi lalajinjin, it's great to see you!


1600

In [88]:
# duck-tying?
sayhi(324035)

Hi 324035, it's great to see you!


In [89]:
A = rand(3, 3)
A
f(A)

3×3 Array{Float64,2}:
 0.827162  1.33412   0.587192
 0.401704  0.858897  0.23807
 1.4556    2.06867   1.21029

In [91]:
f("hi") # string 도 동일하게 처리할 수 있다
# f(*) * 에는 스트링 인풋도 넣을 수 있기 때문이다

"hihi"

In [93]:
# 하지만 f() 함수는 벡터에 사용할 수 없다
v = rand(3)
#f(v) ? 에러남

3-element Array{Float64,1}:
 0.24647542401119082
 0.9578910766840092
 0.10789635247449358

In [96]:
# mutating vs non mutating
# ! 를 사용하는 여부에 따라서 어떤 차이가 있을까?
v = [3, 5, 2]
sort(v) # 해당 결과물을 바꾸지만, 원래 v 를 바꾸지 않음
#in_place = False 느낌
v


3-element Array{Int64,1}:
 2
 3
 5

In [98]:
sort!(v) # 원래 v 까지 바꾸어버림, in_place = True
v

3-element Array{Int64,1}:
 2
 3
 5

In [99]:
# 다른 여러 상위 함수
# map 

In [100]:
map(f, [1,2,3]) # f 라는 함수에 각각을 넣은 결과를 내보낸다

3-element Array{Int64,1}:
 1
 4
 9

In [101]:
[f(1), f(2), f(30)]

3-element Array{Int64,1}:
   1
   4
 900

In [102]:
map(x -> x^3, [1,2,3]) # 이렇게 함수 식 만들지 않고 직접 진행도 가능

3-element Array{Int64,1}:
  1
  8
 27

In [103]:
# broadcast
broadcast(f, [1,2,3])

3-element Array{Int64,1}:
 1
 4
 9

In [104]:
f.([1,2,3]) 
#broadcast 의 기능을 사용하여 . 점을 찍고 결과물을 얻을 수 있다

3-element Array{Int64,1}:
 1
 4
 9

In [106]:
#  f([1,2,3]) 작동안됨

In [107]:
A = [i + 3 *j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [109]:
B = f.(A)
B

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81